# Generated by Django 3.0 on 2019-12-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
            options={
                'unique_together': {('name', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refillDate', models.DateField()),
                ('mileage', models.IntegerField(unique=True)),
                ('liters', models.SmallIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
                ('gas_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fuel.GasStation')),
            ],
        ),
    ]
